let words = 
{
	szinek: [
		{magyar: "barna",spanyol: "pardo, marrón"},
		{magyar: "fehér",spanyol: "blanco"},
		{magyar: "fekete",spanyol: "negro"},
		{magyar: "kék",spanyol: "azul"},
		{magyar: "narancssárga",spanyol: "anaranjado"},
		{magyar: "piros",spanyol: "rojo"},
		{magyar: "rózsaszín",spanyol: "rosado"},
		{magyar: "sárga",spanyol: "amarillo"},
		{magyar: "szürke",spanyol: "gris"},
		{magyar: "zöld",spanyol: "verde"}
	],
	csalad: [
		{magyar: "anya",spanyol: "la madre"},
		{magyar: "anyós",spanyol: "la suegra"},
		{magyar: "apa",spanyol: "el padre"},
		{magyar: "após",spanyol: "el suegro"},
		{magyar: "árva",spanyol: "(el) huérfano"},
		{magyar: "elvált",spanyol: "divorciado"},
		{magyar: "feleség",spanyol: "la mujer"},
		{magyar: "férj",spanyol: "el marido"},
		{magyar: "fia (vkinek)",spanyol: "el hijo"},
		{magyar: "fivér",spanyol: "el hermano"},
		{magyar: "házas",spanyol: "casado"},
		{magyar: "iker",spanyol: "el gemelo"},
		{magyar: "lánya (vkinek)",spanyol: "la hija"},
		{magyar: "meny",spanyol: "la nuera"},
		{magyar: "mostohaanya",spanyol: "la madrastra"},
		{magyar: "mostohaapa",spanyol: "el padrastro"},
		{magyar: "mostohagyerek",spanyol: "el hijastro"},
		{magyar: "nagybácsi",spanyol: "el tío"},
		{magyar: "nagymama",spanyol: "la abuela"},
		{magyar: "nagynéni",spanyol: "la tía"},
		{magyar: "nagypapa",spanyol: "el abuelo"},
		{magyar: "nővér",spanyol: "la hermana"},
		{magyar: "özvegy",spanyol: "(el) viudo"},
		{magyar: "sógor",spanyol: "el cuñado"},
		{magyar: "sógornő",spanyol: "la cuñada"},
		{magyar: "szülők",spanyol: "los padres"},
		{magyar: "unoka",spanyol: "el nieto"},
		{magyar: "unokahúg",spanyol: "la sobrina"},
		{magyar: "unokaöcs",spanyol: "el sobrino"},
		{magyar: "unokatestvér",spanyol: "el primo"},
		{magyar: "vő",spanyol: "el yerno"}
	],
	szamok: [
		{magyar: "0",spanyol: "cero"},
		{magyar: "1",spanyol: "uno"},
		{magyar: "2",spanyol: "dos"},
		{magyar: "3",spanyol: "tres"},
		{magyar: "4",spanyol: "cuatro"},
		{magyar: "5",spanyol: "cinco"},
		{magyar: "6",spanyol: "seis"},
		{magyar: "7",spanyol: "siete"},
		{magyar: "8",spanyol: "ocho"},
		{magyar: "9",spanyol: "nueve"},
		{magyar: "10",spanyol: "diez"},
		{magyar: "11",spanyol: "once"},
		{magyar: "12",spanyol: "doce"},
		{magyar: "13",spanyol: "trece"},
		{magyar: "14",spanyol: "catorce"},
		{magyar: "15",spanyol: "quince"},
		{magyar: "16",spanyol: "dieciséis"},
		{magyar: "17",spanyol: "diecisiete"},
		{magyar: "18",spanyol: "dieciocho"},
		{magyar: "19",spanyol: "diecinueve"},
		{magyar: "20",spanyol: "veinte"},
		{magyar: "21",spanyol: "veintiuno"},
		{magyar: "30",spanyol: "treinta"},
		{magyar: "33",spanyol: "treinta y tres"},
		{magyar: "40",spanyol: "cuarenta"},
		{magyar: "47",spanyol: "cuarenta y siete"},
		{magyar: "50",spanyol: "cincuenta"},
		{magyar: "58",spanyol: "cincuenta y ocho"},
		{magyar: "60",spanyol: "sesenta"},
		{magyar: "62",spanyol: "sesenta y dos"},
		{magyar: "70",spanyol: "setenta"},
		{magyar: "75",spanyol: "setenta y cinco"},
		{magyar: "80",spanyol: "ochenta"},
		{magyar: "84",spanyol: "ochenta y cuatro"},
		{magyar: "90",spanyol: "noventa"},
		{magyar: "99",spanyol: "noventa y nueve"},
		{magyar: "100",spanyol: "cien"},
		{magyar: "200",spanyol: "doscientos"},
		{magyar: "300",spanyol: "trescientos"},
		{magyar: "400",spanyol: "cuatrocientos"},
		{magyar: "500",spanyol: "quinientos"},
		{magyar: "600",spanyol: "seiscientos"},
		{magyar: "700",spanyol: "setecientos"},
		{magyar: "800",spanyol: "ochocientos"},
		{magyar: "900",spanyol: "novecientos"},
		{magyar: "1 000",spanyol: "mil"},
		{magyar: "1 001",spanyol: "mil uno"},
		{magyar: "2 000",spanyol: "dos mil"},
		{magyar: "2 006",spanyol: "dos mil seis"},
		{magyar: "100 000",spanyol: "cien mil"},
		{magyar: "1 000 000",spanyol: "millón"},
		{magyar: "1.",spanyol: "primero"},
		{magyar: "2.",spanyol: "segundo"},
		{magyar: "3.",spanyol: "tercero"},
		{magyar: "4.",spanyol: "cuarto"},
		{magyar: "5.",spanyol: "quinto"},
		{magyar: "6.",spanyol: "sexto"},
		{magyar: "7.",spanyol: "séptimo"},
		{magyar: "8.",spanyol: "octavo"},
		{magyar: "9.",spanyol: "noveno"},
		{magyar: "10.",spanyol: "décimo"},
		{magyar: "11.",spanyol: "undécimo"},
		{magyar: "12.",spanyol: "duodécimo"},
		{magyar: "13.",spanyol: "decimotercero"},
		{magyar: "14.",spanyol: "decimocuarto"},
		{magyar: "15.",spanyol: "decimoquinto"},
		{magyar: "16.",spanyol: "decimosexto"},
		{magyar: "17.",spanyol: "decimoséptimo"},
		{magyar: "18.",spanyol: "decimoctavo"},
		{magyar: "19.",spanyol: "decimonoveno"},
		{magyar: "20.",spanyol: "vigésimo"},
		{magyar: "21.",spanyol: "vigésimo primero"},
		{magyar: "30.",spanyol: "trigésimo"},
		{magyar: "33.",spanyol: "trigésimo tercero"},
		{magyar: "40.",spanyol: "cuadragésimo"},
		{magyar: "47.",spanyol: "cuadragésimo séptimo"},
		{magyar: "50.",spanyol: "quincagésimo"},
		{magyar: "60.",spanyol: "sexagésimo"},
		{magyar: "70.",spanyol: "septuagésimo"},
		{magyar: "80.",spanyol: "octogésimo"},
		{magyar: "90.",spanyol: "nonagésimo"},
		{magyar: "100.",spanyol: "centésimo"},
		{magyar: "1 000.",spanyol: "milésimo"},
		{magyar: "1 000 000.",spanyol: "millonésimo"}
	],
	honapok: [
		{magyar: "hétfő",spanyol: "el lunes"},
		{magyar: "kedd",spanyol: "el martes"},
		{magyar: "szerda",spanyol: "el miércoles"},
		{magyar: "csütörtök",spanyol: "el jueves"},
		{magyar: "péntek",spanyol: "el viernes"},
		{magyar: "szombat",spanyol: "el sábado"},
		{magyar: "vasárnap",spanyol: "el domingo"},
		{magyar: "január",spanyol: "enero"},
		{magyar: "február",spanyol: "febrero"},
		{magyar: "március",spanyol: "marzo"},
		{magyar: "április",spanyol: "abril"},
		{magyar: "május",spanyol: "mayo"},
		{magyar: "június",spanyol: "junio"},
		{magyar: "július",spanyol: "julio"},
		{magyar: "augusztus",spanyol: "agosto"},
		{magyar: "szeptember",spanyol: "septiembre"},
		{magyar: "október",spanyol: "octubre"},
		{magyar: "november",spanyol: "noviembre"},
		{magyar: "december",spanyol: "diciembre"},
		{magyar: "tegnapelőtt",spanyol: "anteayer"},
		{magyar: "tegnap",spanyol: "ayer"},
		{magyar: "ma",spanyol: "hoy"},
		{magyar: "holnap",spanyol: "mañana"},
		{magyar: "holnapután",spanyol: "pasado mañana"},
		{magyar: "hajnal",spanyol: "la madrugada"},
		{magyar: "éjfél",spanyol: "la medianoche"},
		{magyar: "dél",spanyol: "el mediodía"},
		{magyar: "délután",spanyol: "la tarde"},
		{magyar: "este",spanyol: "la noche"},
		{magyar: "évszázad",spanyol: "el siglo"},
		{magyar: "évtized",spanyol: "la década"},
		{magyar: "év",spanyol: "el año"},
		{magyar: "hónap",spanyol: "el mes"},
		{magyar: "hét",spanyol: "la semana"},
		{magyar: "nap",spanyol: "el día"}
	],
	allatok: [
		{magyar: "antilop",spanyol: "el antílope"},
		{magyar: "bagoly",spanyol: "el buho"},
		{magyar: "bálna",spanyol: "la ballena"},
		{magyar: "béka",spanyol: "la rana"},
		{magyar: "bika",spanyol: "el toro"},
		{magyar: "bivaly",spanyol: "el búfalo"},
		{magyar: "borjú",spanyol: "el ternero"},
		{magyar: "bölény",spanyol: "el bisonte"},
		{magyar: "cápa",spanyol: "el tiburón"},
		{magyar: "cinege",spanyol: "el paro"},
		{magyar: "csibe",spanyol: "el pollo"},
		{magyar: "csiga",spanyol: "el caracol"},
		{magyar: "csikó",spanyol: "el potro"},
		{magyar: "csimpánz",spanyol: "el chimpancé"},
		{magyar: "csótány",spanyol: "la cucaracha"},
		{magyar: "csuka",spanyol: "el lucio"},
		{magyar: "darázs",spanyol: "la avispa"},
		{magyar: "daru",spanyol: "la grulla"},
		{magyar: "delfin",spanyol: "el delfín"},
		{magyar: "denevér",spanyol: "el murciélago"},
		{magyar: "disznó",spanyol: "el cerdo"},
		{magyar: "ebihal",spanyol: "el renacuajo"},
		{magyar: "egér",spanyol: "el ratón"},
		{magyar: "elefánt",spanyol: "el elefante"},
		{magyar: "fácán",spanyol: "el faisán"},
		{magyar: "farkas",spanyol: "el lobo"},
		{magyar: "fecske",spanyol: "la golondrina"},
		{magyar: "fóka",spanyol: "la foca"},
		{magyar: "fülemüle",spanyol: "el ruiseñor"},
		{magyar: "galamb",spanyol: "la paloma"},
		{magyar: "gepárd",spanyol: "la onza"},
		{magyar: "gida",spanyol: "el cabrito"},
		{magyar: "gólya",spanyol: "la cigüeña"},
		{magyar: "gorilla",spanyol: "el gorila"},
		{magyar: "gyík",spanyol: "el lagarto"},
		{magyar: "hal",spanyol: "el pez"},
		{magyar: "hangya",spanyol: "el hormiga"},
		{magyar: "hattyú",spanyol: "el cisne"},
		{magyar: "héja",spanyol: "el alferraz"},
		{magyar: "hering",spanyol: "el arenque"},
		{magyar: "hiéna",spanyol: "la hiena"},
		{magyar: "hiúz",spanyol: "el lince"},
		{magyar: "hód",spanyol: "el castor"},
		{magyar: "holló",spanyol: "el cuervo"},
		{magyar: "homár",spanyol: "el bogavante"},
		{magyar: "hörcsög",spanyol: "el hámster"},
		{magyar: "jaguár",spanyol: "el jaguar"},
		{magyar: "jegesmedve",spanyol: "el oso polar"},
		{magyar: "juh",spanyol: "la oveja"},
		{magyar: "kacsa",spanyol: "el pato"},
		{magyar: "kakas",spanyol: "el gallo"},
		{magyar: "kakukk",spanyol: "el cuco"},
		{magyar: "kaméleon",spanyol: "el camaleón"},
		{magyar: "kanca",spanyol: "la yegua"},
		{magyar: "kecske",spanyol: "la cabra"},
		{magyar: "kenguru",spanyol: "el canguro"},
		{magyar: "kígyó",spanyol: "la serpiente"},
		{magyar: "kolibri",spanyol: "el colibrí"},
		{magyar: "krokodil",spanyol: "el cocodrilo"},
		{magyar: "kullancs",spanyol: "la garrapata"},
		{magyar: "kutya",spanyol: "el perro"},
		{magyar: "lajhár",spanyol: "el perezoso"},
		{magyar: "lazac",spanyol: "el salmón"},
		{magyar: "légy",spanyol: "la mosca"},
		{magyar: "lepke",spanyol: "la mariposa"},
		{magyar: "liba",spanyol: "la oca"},
		{magyar: "ló",spanyol: "el caballo"},
		{magyar: "macska",spanyol: "el gato"},
		{magyar: "madár",spanyol: "el pájaro"},
		{magyar: "malac",spanyol: "el cochinillo"},
		{magyar: "medúza",spanyol: "la medusa"},
		{magyar: "medve",spanyol: "el oso"},
		{magyar: "méh",spanyol: "la abeja"},
		{magyar: "mókus",spanyol: "la ardilla"},
		{magyar: "mosómedve",spanyol: "el mapache"},
		{magyar: "nyúl",spanyol: "el conejo"},
		{magyar: "oroszlán",spanyol: "el león"},
		{magyar: "orrszarvú",spanyol: "el rinoceronte"},
		{magyar: "osztriga",spanyol: "la ostra"},
		{magyar: "őz",spanyol: "el corzo"},
		{magyar: "pacsirta",spanyol: "la alondra"},
		{magyar: "panda",spanyol: "la panda"},
		{magyar: "papagáj",spanyol: "el loro"},
		{magyar: "párduc",spanyol: "la pantera"},
		{magyar: "patkány",spanyol: "la rata"},
		{magyar: "páva",spanyol: "el pavón"},
		{magyar: "pelikán",spanyol: "el pelícano"},
		{magyar: "pingvin",spanyol: "el pingüino"},
		{magyar: "pisztráng",spanyol: "la trucha"},
		{magyar: "pók",spanyol: "la araña"},
		{magyar: "polip",spanyol: "el pólipo"},
		{magyar: "poloska",spanyol: "el chinche"},
		{magyar: "póni",spanyol: "el poni"},
		{magyar: "ponty",spanyol: "la carpa"},
		{magyar: "pulyka",spanyol: "el pavo"},
		{magyar: "rája",spanyol: "la raya"},
		{magyar: "rák",spanyol: "el cangrejo"},
		{magyar: "róka",spanyol: "el zorro"},
		{magyar: "sakál",spanyol: "el chacal"},
		{magyar: "sas",spanyol: "el águila"},
		{magyar: "sáska",spanyol: "la langosta"},
		{magyar: "seregély",spanyol: "el estornino"},
		{magyar: "sirály",spanyol: "la gaviota"},
		{magyar: "skorpió",spanyol: "el escorpión"},
		{magyar: "sólyom",spanyol: "el halcón"},
		{magyar: "strucc",spanyol: "el avestruz"},
		{magyar: "sün",spanyol: "el erizo"},
		{magyar: "szamár",spanyol: "el burro"},
		{magyar: "szarvas",spanyol: "el ciervo"},
		{magyar: "szarvasbogár",spanyol: "el ciervo volante"},
		{magyar: "szúnyog",spanyol: "el mosquito"},
		{magyar: "tehén",spanyol: "la vaca"},
		{magyar: "teknős",spanyol: "la tortuga"},
		{magyar: "tengerimalac",spanyol: "la cobaya"},
		{magyar: "tetű",spanyol: "el piojo"},
		{magyar: "teve",spanyol: "el camello"},
		{magyar: "tigris",spanyol: "el tigre"},
		{magyar: "tintahal",spanyol: "el calamar"},
		{magyar: "tonhal",spanyol: "el atún"},
		{magyar: "tücsök",spanyol: "el grillo"},
		{magyar: "tyúk",spanyol: "la gallina"},
		{magyar: "vadászgörény",spanyol: "el hurón"},
		{magyar: "vaddisznó",spanyol: "el jabalí"},
		{magyar: "vakond",spanyol: "el topo"},
		{magyar: "varangy",spanyol: "el sapo"},
		{magyar: "veréb",spanyol: "el gorrión"},
		{magyar: "vidra",spanyol: "la nutria"},
		{magyar: "vipera",spanyol: "la víbora"},
		{magyar: "viziló",spanyol: "el hipopótamo"},
		{magyar: "zebra",spanyol: "la cebra"},
		{magyar: "zerge",spanyol: "la gamuza"},
		{magyar: "zsiráf",spanyol: "la jirafa"}
	],
	tulajdonsagok: [
		{magyar: "alacsony",spanyol: "bajo"},
		{magyar: "becsületes",spanyol: "honesto"},
		{magyar: "beteg",spanyol: "enfermo"},
		{magyar: "boldog",spanyol: "feliz"},
		{magyar: "bonyolult",spanyol: "complicado"},
		{magyar: "buta",spanyol: "tonto"},
		{magyar: "csinos",spanyol: "guapo"},
		{magyar: "csúnya",spanyol: "feo"},
		{magyar: "drága",spanyol: "caro"},
		{magyar: "édes",spanyol: "dulce"},
		{magyar: "egészséges",spanyol: "sano"},
		{magyar: "egyszerű",spanyol: "sencillo"},
		{magyar: "érdekes",spanyol: "interesante"},
		{magyar: "erős",spanyol: "fuerte"},
		{magyar: "fáradt",spanyol: "cansado"},
		{magyar: "fiatal",spanyol: "joven"},
		{magyar: "gazdag",spanyol: "rico"},
		{magyar: "gyenge",spanyol: "débil"},
		{magyar: "gyors",spanyol: "rápido"},
		{magyar: "hideg",spanyol: "frío"},
		{magyar: "hosszú",spanyol: "largo"},
		{magyar: "ideges",spanyol: "nervioso"},
		{magyar: "igazságos",spanyol: "justo"},
		{magyar: "igazságtalan",spanyol: "injusto"},
		{magyar: "jó",spanyol: "bueno"},
		{magyar: "kemény",spanyol: "duro"},
		{magyar: "keserű",spanyol: "amargo"},
		{magyar: "keskeny",spanyol: "estrecho"},
		{magyar: "kevés",spanyol: "poco"},
		{magyar: "kicsi",spanyol: "pequeño"},
		{magyar: "kíváncsi",spanyol: "curioso"},
		{magyar: "könnyű",spanyol: "fácil"},
		{magyar: "kövér",spanyol: "gordo"},
		{magyar: "lassú",spanyol: "lento"},
		{magyar: "lusta",spanyol: "perezoso"},
		{magyar: "magas",spanyol: "alto"},
		{magyar: "meleg",spanyol: "caliente"},
		{magyar: "nagy",spanyol: "grande"},
		{magyar: "nehéz",spanyol: "difícil"},
		{magyar: "nyugodt",spanyol: "tranquilo"},
		{magyar: "olcsó",spanyol: "barato"},
		{magyar: "öreg",spanyol: "viejo"},
		{magyar: "piszkos",spanyol: "sucio"},
		{magyar: "régi",spanyol: "antiguo"},
		{magyar: "rossz",spanyol: "malo"},
		{magyar: "rövid",spanyol: "corto"},
		{magyar: "sok",spanyol: "mucho"},
		{magyar: "sós",spanyol: "salado"},
		{magyar: "sovány",spanyol: "flaco"},
		{magyar: "sötét",spanyol: "oscuro"},
		{magyar: "száraz",spanyol: "seco"},
		{magyar: "szegény",spanyol: "pobre"},
		{magyar: "széles",spanyol: "ancho"},
		{magyar: "szép",spanyol: "hermoso"},
		{magyar: "szerény",spanyol: "modesto"},
		{magyar: "szomorú",spanyol: "triste"},
		{magyar: "szórakoztató",spanyol: "divertido"},
		{magyar: "szorgalmas",spanyol: "aplicado"},
		{magyar: "teli",spanyol: "lleno"},
		{magyar: "tiszta",spanyol: "puro"},
		{magyar: "udvarias",spanyol: "cortés"},
		{magyar: "új",spanyol: "nuevo"},
		{magyar: "unalmas",spanyol: "aburrido"},
		{magyar: "üres",spanyol: "vacío"},
		{magyar: "vastag",spanyol: "grueso"},
		{magyar: "vékony",spanyol: "delgado"},
		{magyar: "vidám",spanyol: "alegre"},
		{magyar: "világos",spanyol: "claro"}
	],
	ruhazat: [
		{magyar: "alsónemű",spanyol: "la ropa interior"},
		{magyar: "bársony",spanyol: "el terciopelo"},
		{magyar: "blúz",spanyol: "la blusa"},
		{magyar: "bőr",spanyol: "el cuero"},
		{magyar: "cipő",spanyol: "los zapatos"},
		{magyar: "cipzár",spanyol: "la cremallera"},
		{magyar: "csizma",spanyol: "las botas"},
		{magyar: "esőkabát",spanyol: "el impermeable"},
		{magyar: "flanell",spanyol: "la franela"},
		{magyar: "gomb",spanyol: "el botón"},
		{magyar: "gyapjú",spanyol: "la lana"},
		{magyar: "hálóing",spanyol: "el camisón"},
		{magyar: "ing",spanyol: "la camisa"},
		{magyar: "ingujj",spanyol: "la manga"},
		{magyar: "kabát",spanyol: "el abrigo"},
		{magyar: "kalap",spanyol: "el sombrero"},
		{magyar: "kendő",spanyol: "el pañuelo"},
		{magyar: "kesztyű",spanyol: "los guantes"},
		{magyar: "kordbársony",spanyol: "la pana"},
		{magyar: "köpeny",spanyol: "la bata"},
		{magyar: "mellény",spanyol: "el chaleco"},
		{magyar: "nadrág",spanyol: "el pantalón"},
		{magyar: "napszemüveg",spanyol: "las gafas de sol"},
		{magyar: "nyakkendő",spanyol: "la corbata"},
		{magyar: "öltöny",spanyol: "el traje"},
		{magyar: "öv",spanyol: "el cinturón"},
		{magyar: "pamut",spanyol: "el algodón"},
		{magyar: "papucs",spanyol: "las zapatillas"},
		{magyar: "pizsama",spanyol: "el pijama"},
		{magyar: "rövidnadrág",spanyol: "el pantalón corto"},
		{magyar: "ruha",spanyol: "la ropa"},
		{magyar: "sál",spanyol: "la bufanda"},
		{magyar: "sapka",spanyol: "el gorro"},
		{magyar: "selyem",spanyol: "la seda"},
		{magyar: "szabadidőruha",spanyol: "el chándal"},
		{magyar: "szmoking",spanyol: "el esmoquin"},
		{magyar: "szoknya",spanyol: "la falda"},
		{magyar: "szvetter",spanyol: "el suéter"},
		{magyar: "zakó",spanyol: "la chaqueta"},
		{magyar: "zokni",spanyol: "el calcetín"},
		{magyar: "zseb",spanyol: "el bolsillo"}
	],
	sport: [
		{magyar: "asztalitenisz",spanyol: "el tenis de mesa"},
		{magyar: "atlétika",spanyol: "el atletismo"},
		{magyar: "bajnokság",spanyol: "el campeonato"},
		{magyar: "diszkoszvetés",spanyol: "el lanzamiento de disco"},
		{magyar: "döntetlen",spanyol: "el empate"},
		{magyar: "gerelyhajítás",spanyol: "el lanzamiento de jabalina"},
		{magyar: "jégkorong",spanyol: "el hockey hielo"},
		{magyar: "kerékpározás",spanyol: "el ciclismo"},
		{magyar: "kézilabda",spanyol: "el balonmano"},
		{magyar: "kosárlabda",spanyol: "el baloncesto"},
		{magyar: "kupa",spanyol: "la copa"},
		{magyar: "labdarúgás",spanyol: "el fútbol"},
		{magyar: "lovaglás",spanyol: "la equitación"},
		{magyar: "magasugrás",spanyol: "el salto de altura"},
		{magyar: "mérkőzés",spanyol: "el partido"},
		{magyar: "ökölvívás",spanyol: "el boxeo"},
		{magyar: "öttusa",spanyol: "el pentatlón"},
		{magyar: "röplabda",spanyol: "el voleibol"},
		{magyar: "rúdugrás",spanyol: "el salto con pértiga"},
		{magyar: "sakk",spanyol: "el ajedrez"},
		{magyar: "síelés",spanyol: "el esquí"},
		{magyar: "sport",spanyol: "el deporte"},
		{magyar: "sportoló",spanyol: "el/la deportista"},
		{magyar: "távolugrás",spanyol: "el salto de longitud"},
		{magyar: "tenisz",spanyol: "el tenis"},
		{magyar: "tollaslabda",spanyol: "el bádminton"},
		{magyar: "torna",spanyol: "la gimnasia"},
		{magyar: "úszás",spanyol: "la natación"},
		{magyar: "vitorlázás",spanyol: "la vela"},
		{magyar: "vizilabda",spanyol: "el waterpolo"}
	],
	elelmiszerek: [
		{magyar: "almabor",spanyol: "la sidra"},
		{magyar: "ásványvíz",spanyol: "el agua mineral"},
		{magyar: "bonbon",spanyol: "el bombón"},
		{magyar: "bor",spanyol: "el vino"},
		{magyar: "bors",spanyol: "la pimienta"},
		{magyar: "cukor",spanyol: "el azúcar"},
		{magyar: "csokoládé",spanyol: "el chocolate"},
		{magyar: "ecet",spanyol: "el vinagre"},
		{magyar: "fagylalt",spanyol: "el helado"},
		{magyar: "fahéj",spanyol: "la canela"},
		{magyar: "fűszer",spanyol: "la especia"},
		{magyar: "gyümölcslé",spanyol: "el zumo"},
		{magyar: "hal",spanyol: "el pescado"},
		{magyar: "hús",spanyol: "la carne"},
		{magyar: "joghurt",spanyol: "el yogurt"},
		{magyar: "kakaó",spanyol: "el cacao"},
		{magyar: "kalács",spanyol: "el bollo"},
		{magyar: "kávé",spanyol: "el café"},
		{magyar: "kefír",spanyol: "el kéfir"},
		{magyar: "keksz",spanyol: "la galleta"},
		{magyar: "kenyér",spanyol: "el pan"},
		{magyar: "kifli",spanyol: "la medialuna"},
		{magyar: "kolbász",spanyol: "el chorizo"},
		{magyar: "konzerv",spanyol: "la conserva"},
		{magyar: "liszt",spanyol: "la harina"},
		{magyar: "margarin",spanyol: "la margarina"},
		{magyar: "mazsola",spanyol: "la uva pasa"},
		{magyar: "méz",spanyol: "la miel"},
		{magyar: "mustár",spanyol: "la mostaza"},
		{magyar: "olívaolaj",spanyol: "el aceite de oliva"},
		{magyar: "pálinka",spanyol: "el aguardiente"},
		{magyar: "pezsgő",spanyol: "el champán"},
		{magyar: "puding",spanyol: "el pudín"},
		{magyar: "rizs",spanyol: "el arroz"},
		{magyar: "sajt",spanyol: "el queso"},
		{magyar: "só",spanyol: "la sal"},
		{magyar: "sonka",spanyol: "el jamón"},
		{magyar: "sör",spanyol: "la cerveza"},
		{magyar: "szalámi",spanyol: "el salchichón"},
		{magyar: "tea",spanyol: "el té"},
		{magyar: "tej",spanyol: "la leche"},
		{magyar: "tejpor",spanyol: "la leche en polvo"},
		{magyar: "tejszín",spanyol: "la nata"},
		{magyar: "tojás",spanyol: "el huevo"},
		{magyar: "túró",spanyol: "el requesón"},
		{magyar: "üdítőital",spanyol: "el refresco"},
		{magyar: "vaj",spanyol: "la mantequilla"},
		{magyar: "virsli",spanyol: "la salchicha"},
		{magyar: "víz",spanyol: "el agua"},
		{magyar: "zsemle",spanyol: "el panecillo"}
	],
	szakmak: [
		{magyar: "alkalmazott",spanyol: "el empleado"},
		{magyar: "állatorvos",spanyol: "el veterinario"},
		{magyar: "ápoló",spanyol: "el enfermero"},
		{magyar: "asztalos",spanyol: "el carpintero"},
		{magyar: "bankár",spanyol: "el banquero"},
		{magyar: "bányász",spanyol: "el minero"},
		{magyar: "bíró",spanyol: "el/la juez"},
		{magyar: "cipész",spanyol: "el zapatero"},
		{magyar: "cukrász",spanyol: "el pastelero"},
		{magyar: "ékszerész",spanyol: "el joyero"},
		{magyar: "eladó",spanyol: "el/la dependiente"},
		{magyar: "énekes",spanyol: "el/la cantante"},
		{magyar: "építész",spanyol: "el arquitecto"},
		{magyar: "fényképész",spanyol: "el fotógrafo"},
		{magyar: "festő",spanyol: "el pintor"},
		{magyar: "fodrász",spanyol: "el peluquero"},
		{magyar: "fogorvos",spanyol: "el/la dentista"},
		{magyar: "fordító",spanyol: "el traductor"},
		{magyar: "földműves",spanyol: "el agricultor"},
		{magyar: "gyógyszerész",spanyol: "el farmacéutico"},
		{magyar: "halász",spanyol: "el pescador"},
		{magyar: "háziasszony",spanyol: "el ama de casa"},
		{magyar: "hentes",spanyol: "el carnicero"},
		{magyar: "író",spanyol: "el escritor"},
		{magyar: "jegyző",spanyol: "el notario"},
		{magyar: "jogász",spanyol: "el/la jurista"},
		{magyar: "kárpitos",spanyol: "el tapicero"},
		{magyar: "katona",spanyol: "el soldado"},
		{magyar: "képviselő",spanyol: "el diputado"},
		{magyar: "kereskedő",spanyol: "el comerciante"},
		{magyar: "kertész",spanyol: "el jardinero"},
		{magyar: "kézműves",spanyol: "el artesano"},
		{magyar: "kovács",spanyol: "el herrero"},
		{magyar: "költő",spanyol: "el poeta"},
		{magyar: "kőműves",spanyol: "el albañil"},
		{magyar: "könyvelő",spanyol: "el contable"},
		{magyar: "könyvtáros",spanyol: "el bibliotecario"},
		{magyar: "közgazdász",spanyol: "el/la economista"},
		{magyar: "látszerész",spanyol: "el óptico"},
		{magyar: "mérnök",spanyol: "el ingeniero"},
		{magyar: "munkanélküli",spanyol: "(el) desempleado"},
		{magyar: "munkás",spanyol: "el obrero"},
		{magyar: "művész",spanyol: "el/la artista"},
		{magyar: "nagykereskedő",spanyol: "el mayorista"},
		{magyar: "nyelvész",spanyol: "el/la lingüista"},
		{magyar: "nyomdász",spanyol: "el tipógrafo"},
		{magyar: "nyugdíjas",spanyol: "el/la pensionista"},
		{magyar: "órás",spanyol: "el relojero"},
		{magyar: "orvos",spanyol: "el médico"},
		{magyar: "pap",spanyol: "el cura"},
		{magyar: "pedagógus",spanyol: "el pedagogo"},
		{magyar: "pék",spanyol: "el panadero"},
		{magyar: "pilóta",spanyol: "el piloto"},
		{magyar: "pincér",spanyol: "el camarero"},
		{magyar: "postás",spanyol: "el cartero"},
		{magyar: "pszichológus",spanyol: "el psicólogo"},
		{magyar: "riporter",spanyol: "el reportero"},
		{magyar: "sofőr",spanyol: "el chófer"},
		{magyar: "szabó",spanyol: "el sastre"},
		{magyar: "szakács",spanyol: "el cocinero"},
		{magyar: "szakértő",spanyol: "el experto"},
		{magyar: "szerelő",spanyol: "el mecánico"},
		{magyar: "szerkesztő",spanyol: "el redactor"},
		{magyar: "színész",spanyol: "el actor"},
		{magyar: "színésznő",spanyol: "la actriz"},
		{magyar: "szobrász",spanyol: "el escultor"},
		{magyar: "tanár",spanyol: "el profesor"},
		{magyar: "táncos",spanyol: "el bailarín"},
		{magyar: "tanító",spanyol: "el maestro"},
		{magyar: "tengerész",spanyol: "el marinero"},
		{magyar: "titkár",spanyol: "el secretario"},
		{magyar: "tolmács",spanyol: "el intérprete"},
		{magyar: "tudós",spanyol: "el científico"},
		{magyar: "tűzoltó",spanyol: "el bombero"},
		{magyar: "újságíró",spanyol: "el/la periodista"},
		{magyar: "ügyvéd",spanyol: "el abogado"},
		{magyar: "üveges",spanyol: "el vidriero"},
		{magyar: "vadász",spanyol: "el cazador"},
		{magyar: "vámos",spanyol: "el aduanero"},
		{magyar: "vasutas",spanyol: "el ferroviario"},
		{magyar: "vegyész",spanyol: "el químico"},
		{magyar: "villanyszerelő",spanyol: "el/la electricista"},
		{magyar: "virágárus",spanyol: "el/la florista"},
		{magyar: "vízvezeték-szerelő",spanyol: "el fontanero"},
		{magyar: "zenész",spanyol: "el músico"}
	],
	zoldseg: [
		{magyar: "áfonya",spanyol: "el arándano"},
		{magyar: "alma",spanyol: "la manzana"},
		{magyar: "ananász",spanyol: "la piña"},
		{magyar: "articsóka",spanyol: "la alcachofa"},
		{magyar: "avokádó",spanyol: "el aguacate"},
		{magyar: "bab",spanyol: "la judía"},
		{magyar: "banán",spanyol: "el plátano"},
		{magyar: "bazsalikom",spanyol: "la albahaca"},
		{magyar: "birsalma",spanyol: "el membrillo"},
		{magyar: "bodza",spanyol: "el saúco"},
		{magyar: "bors",spanyol: "la pimienta"},
		{magyar: "brokkoli",spanyol: "el brécol"},
		{magyar: "burgonya",spanyol: "la patata"},
		{magyar: "cikória",spanyol: "la achicoria"},
		{magyar: "citrom",spanyol: "el limón"},
		{magyar: "cseresznye",spanyol: "la cereza"},
		{magyar: "csipkebogyó",spanyol: "el escaramujo"},
		{magyar: "datolya",spanyol: "el dátil"},
		{magyar: "dió",spanyol: "la nuez"},
		{magyar: "eper",spanyol: "la fresa"},
		{magyar: "fokhagyma",spanyol: "el ajo"},
		{magyar: "füge",spanyol: "el higo"},
		{magyar: "gesztenye",spanyol: "la castaña"},
		{magyar: "gomba",spanyol: "la seta"},
		{magyar: "görögdinnye",spanyol: "la sandía"},
		{magyar: "kapor",spanyol: "el eneldo"},
		{magyar: "káposzta",spanyol: "el repollo"},
		{magyar: "karalábé",spanyol: "el colinabo"},
		{magyar: "karfiol",spanyol: "la coliflor"},
		{magyar: "kelbimbó",spanyol: "el bretón"},
		{magyar: "kökény",spanyol: "la endrina"},
		{magyar: "kömény",spanyol: "el comino"},
		{magyar: "körte",spanyol: "la pera"},
		{magyar: "kukorica",spanyol: "el maíz"},
		{magyar: "lencse",spanyol: "la lenteja"},
		{magyar: "málna",spanyol: "la frambuesa"},
		{magyar: "mandarin",spanyol: "la mandarina"},
		{magyar: "mandula",spanyol: "la almendra"},
		{magyar: "mangó",spanyol: "el mango"},
		{magyar: "meggy",spanyol: "la guinda"},
		{magyar: "narancs",spanyol: "la naranja"},
		{magyar: "naspolya",spanyol: "la níspola"},
		{magyar: "őszibarack",spanyol: "el melocotón"},
		{magyar: "padlizsán",spanyol: "la berenjena"},
		{magyar: "paprika",spanyol: "el pimiento"},
		{magyar: "paradicsom",spanyol: "el tomate"},
		{magyar: "paraj",spanyol: "la espinaca"},
		{magyar: "petrezselyem",spanyol: "el perejil"},
		{magyar: "rebarbara",spanyol: "el ruibarbo"},
		{magyar: "retek",spanyol: "el rábano"},
		{magyar: "ribizli",spanyol: "la grosella"},
		{magyar: "sárgabarack",spanyol: "el albaricoque"},
		{magyar: "sárgadinnye",spanyol: "el melón"},
		{magyar: "sárgarépa",spanyol: "la zanahoria"},
		{magyar: "sóska",spanyol: "la acedera"},
		{magyar: "spárga",spanyol: "el espárrago"},
		{magyar: "szamóca",spanyol: "la fresa silvestre"},
		{magyar: "szarvasgomba",spanyol: "la trufa"},
		{magyar: "szeder",spanyol: "la zarzamora"},
		{magyar: "szilva",spanyol: "la ciruela"},
		{magyar: "szőlő",spanyol: "la uva"},
		{magyar: "torma",spanyol: "el rábano picante"},
		{magyar: "tök",spanyol: "la calabaza"},
		{magyar: "uborka",spanyol: "el pepino"},
		{magyar: "zeller",spanyol: "el apio"},
		{magyar: "zöldbab",spanyol: "las judías verdes"},
		{magyar: "zöldborsó",spanyol: "el guisante"}
	],
	otthon: [
		{magyar: "ablak",spanyol: "la ventana"},
		{magyar: "ágy",spanyol: "la cama"},
		{magyar: "ajtó",spanyol: "la puerta"},
		{magyar: "asztal",spanyol: "la mesa"},
		{magyar: "bútor",spanyol: "el mueble"},
		{magyar: "csap",spanyol: "el grifo"},
		{magyar: "csempe",spanyol: "el azulejo"},
		{magyar: "csésze",spanyol: "la taza"},
		{magyar: "előszoba",spanyol: "el vestíbulo"},
		{magyar: "erkély",spanyol: "el balcón"},
		{magyar: "fal",spanyol: "la pared"},
		{magyar: "falióra",spanyol: "el reloj de pared"},
		{magyar: "faliszekrény",spanyol: "la alacena"},
		{magyar: "fiók",spanyol: "el cajón"},
		{magyar: "fotel",spanyol: "el sillón"},
		{magyar: "függöny",spanyol: "la cortina"},
		{magyar: "fürdőkád",spanyol: "la bañera"},
		{magyar: "fürdőszoba",spanyol: "el baño"},
		{magyar: "fűtőtest",spanyol: "el radiador"},
		{magyar: "hálószoba",spanyol: "el dormitorio"},
		{magyar: "ház",spanyol: "la casa"},
		{magyar: "hűtőszekrény",spanyol: "el refrigerador, la nevera"},
		{magyar: "íróasztal",spanyol: "el escritorio"},
		{magyar: "kamra",spanyol: "la despensa"},
		{magyar: "kanál",spanyol: "la cuchara"},
		{magyar: "kert",spanyol: "el jardín"},
		{magyar: "kés",spanyol: "el cuchillo"},
		{magyar: "kilincs",spanyol: "el picaporte"},
		{magyar: "konyha",spanyol: "la cocina"},
		{magyar: "könyv",spanyol: "el libro"},
		{magyar: "kulcs",spanyol: "la llave"},
		{magyar: "lámpa",spanyol: "la lámpara"},
		{magyar: "lepedő",spanyol: "la sábana"},
		{magyar: "mennyezet",spanyol: "el techo"},
		{magyar: "mosdókagyló",spanyol: "el lavabo"},
		{magyar: "mosogató",spanyol: "el fregadero"},
		{magyar: "padlás",spanyol: "el desván"},
		{magyar: "padló",spanyol: "el piso"},
		{magyar: "palack",spanyol: "la botella"},
		{magyar: "papír",spanyol: "el papel"},
		{magyar: "párna",spanyol: "la almohada"},
		{magyar: "pince",spanyol: "el sótano"},
		{magyar: "pohár",spanyol: "el vaso"},
		{magyar: "sütő",spanyol: "el horno"},
		{magyar: "szalvéta",spanyol: "la servilleta"},
		{magyar: "számítógép",spanyol: "el computador"},
		{magyar: "szék",spanyol: "la silla"},
		{magyar: "szekrény",spanyol: "el armario"},
		{magyar: "szoba",spanyol: "el cuarto"},
		{magyar: "szőnyeg",spanyol: "la alfombra"},
		{magyar: "tál",spanyol: "el plato"},
		{magyar: "tapéta",spanyol: "el empapelado"},
		{magyar: "telefon",spanyol: "el teléfono"},
		{magyar: "terasz",spanyol: "la terraza"},
		{magyar: "tetőcserép",spanyol: "la teja"},
		{magyar: "tévé",spanyol: "la tele"},
		{magyar: "toll",spanyol: "la pluma"},
		{magyar: "törölköző",spanyol: "la toalla"},
		{magyar: "tükör",spanyol: "el espejo"},
		{magyar: "tűzhely",spanyol: "el fogón"},
		{magyar: "vasaló",spanyol: "la plancha"},
		{magyar: "villa",spanyol: "el tenedor"},
		{magyar: "virág",spanyol: "la flor"},
		{magyar: "virágcserép",spanyol: "la maceta"},
		{magyar: "zuhany",spanyol: "la ducha"}
	],
	testreszek: [
		{magyar: "agy",spanyol: "el cerebro"},
		{magyar: "ajak",spanyol: "el labio"},
		{magyar: "arc",spanyol: "la cara"},
		{magyar: "bajusz",spanyol: "el bigote"},
		{magyar: "bél",spanyol: "el intestino"},
		{magyar: "boka",spanyol: "el tobillo"},
		{magyar: "bőr",spanyol: "la piel"},
		{magyar: "comb",spanyol: "el muslo"},
		{magyar: "csípő",spanyol: "la cadera"},
		{magyar: "csont",spanyol: "el hueso"},
		{magyar: "csontváz",spanyol: "el esqueleto"},
		{magyar: "csukló",spanyol: "la muñeca"},
		{magyar: "derék",spanyol: "la cintura"},
		{magyar: "fej",spanyol: "la cabeza"},
		{magyar: "fog",spanyol: "el diente"},
		{magyar: "fül",spanyol: "la oreja"},
		{magyar: "gerinc",spanyol: "el espinazo"},
		{magyar: "gyomor",spanyol: "el estómago"},
		{magyar: "gyűrűsujj",spanyol: "el dedo anular"},
		{magyar: "haj",spanyol: "el pelo"},
		{magyar: "halánték",spanyol: "la sien"},
		{magyar: "has",spanyol: "el vientre"},
		{magyar: "hát",spanyol: "la espalda"},
		{magyar: "homlok",spanyol: "la frente"},
		{magyar: "hónalj",spanyol: "la axila"},
		{magyar: "hüvelykujj",spanyol: "el pulgar"},
		{magyar: "ideg",spanyol: "el nervio"},
		{magyar: "izom",spanyol: "el músculo"},
		{magyar: "kar",spanyol: "el brazo"},
		{magyar: "kéz",spanyol: "la mano"},
		{magyar: "kisujj",spanyol: "el dedillo"},
		{magyar: "koponya",spanyol: "el cráneo"},
		{magyar: "könyök",spanyol: "el codo"},
		{magyar: "köröm",spanyol: "la uña"},
		{magyar: "lábfej",spanyol: "el pie"},
		{magyar: "lábszár",spanyol: "la pierna"},
		{magyar: "lábujj",spanyol: "el dedo del pie"},
		{magyar: "máj",spanyol: "el hígado"},
		{magyar: "méh",spanyol: "el útero"},
		{magyar: "mell",spanyol: "el pecho"},
		{magyar: "mutatóujj",spanyol: "el índice"},
		{magyar: "nyak",spanyol: "el cuello"},
		{magyar: "nyelv",spanyol: "la lengua"},
		{magyar: "orca",spanyol: "la mejilla"},
		{magyar: "orr",spanyol: "la nariz"},
		{magyar: "ököl",spanyol: "el puño"},
		{magyar: "sarok",spanyol: "el talón"},
		{magyar: "száj",spanyol: "la boca"},
		{magyar: "szakáll",spanyol: "la barba"},
		{magyar: "szem",spanyol: "el ojo"},
		{magyar: "szemöldök",spanyol: "la ceja"},
		{magyar: "szempilla",spanyol: "la pestaña"},
		{magyar: "szerv",spanyol: "el órgano"},
		{magyar: "szív",spanyol: "el corazón"},
		{magyar: "talp",spanyol: "la planta"},
		{magyar: "tarkó",spanyol: "la nuca"},
		{magyar: "tenyér",spanyol: "la palma"},
		{magyar: "térd",spanyol: "la rodilla"},
		{magyar: "test",spanyol: "el cuerpo"},
		{magyar: "torok",spanyol: "la garganta"},
		{magyar: "tüdő",spanyol: "el pulmón"},
		{magyar: "ujj",spanyol: "el dedo"},
		{magyar: "váll",spanyol: "el hombro"},
		{magyar: "vér",spanyol: "la sangre"},
		{magyar: "vese",spanyol: "el riñón"}
	],
	varos: [
		{magyar: "áruház",spanyol: "el almacén"},
		{magyar: "bank",spanyol: "el banco"},
		{magyar: "benzinkút",spanyol: "la gasolinera"},
		{magyar: "bolt",spanyol: "la tienda"},
		{magyar: "étterem",spanyol: "el restaurante"},
		{magyar: "fogadó",spanyol: "la posada"},
		{magyar: "gyógyszertár",spanyol: "la farmacia"},
		{magyar: "iskola",spanyol: "la escuela"},
		{magyar: "járda",spanyol: "la acera"},
		{magyar: "kávéház",spanyol: "la cafetería"},
		{magyar: "kirakat",spanyol: "el escaparate"},
		{magyar: "kórház",spanyol: "el hospital"},
		{magyar: "könyvesbolt",spanyol: "la librería"},
		{magyar: "könyvtár",spanyol: "la biblioteca"},
		{magyar: "megálló",spanyol: "la parada"},
		{magyar: "múzeum",spanyol: "el museo"},
		{magyar: "óvoda",spanyol: "la guardería"},
		{magyar: "önkormányzat",spanyol: "la municipalidad"},
		{magyar: "piac",spanyol: "el mercado"},
		{magyar: "rendőrség",spanyol: "la policía"},
		{magyar: "repülőtér",spanyol: "el aeropuerto"},
		{magyar: "söröző",spanyol: "la cervecería"},
		{magyar: "stadion",spanyol: "el estadio"},
		{magyar: "tűzoltóság",spanyol: "la estación de bomberos"},
		{magyar: "vasútállomás",spanyol: "la estación de ferrocarril"}
	],
	uzlet: [
		{magyar: "adó",spanyol: "el impuesto"},
		{magyar: "adósság",spanyol: "la deuda"},
		{magyar: "ár",spanyol: "el precio"},
		{magyar: "áru",spanyol: "la mercancía"},
		{magyar: "árverés",spanyol: "la subasta"},
		{magyar: "bank",spanyol: "el banco"},
		{magyar: "bevétel",spanyol: "el ingreso"},
		{magyar: "biztosítás",spanyol: "el seguro"},
		{magyar: "bolt",spanyol: "la tienda"},
		{magyar: "csőd",spanyol: "la quiebra"},
		{magyar: "deviza",spanyol: "la divisa"},
		{magyar: "egyenleg",spanyol: "el saldo"},
		{magyar: "exportőr",spanyol: "el exportador"},
		{magyar: "fogyasztás",spanyol: "el consumo"},
		{magyar: "fogyasztó",spanyol: "el consumidor"},
		{magyar: "források",spanyol: "los recursos"},
		{magyar: "gazdaság",spanyol: "la economía"},
		{magyar: "haszon",spanyol: "el lucro"},
		{magyar: "hitel",spanyol: "el crédito"},
		{magyar: "importőr",spanyol: "el importador"},
		{magyar: "ipar",spanyol: "la industria"},
		{magyar: "javak",spanyol: "los bienes"},
		{magyar: "kamat",spanyol: "el interés"},
		{magyar: "kereskedelem",spanyol: "el comercio"},
		{magyar: "kereslet",spanyol: "la demanda"},
		{magyar: "kiadás",spanyol: "el gasto"},
		{magyar: "kínálat",spanyol: "la oferta"},
		{magyar: "könyvvizsgálat",spanyol: "la auditoría"},
		{magyar: "leányvállalat",spanyol: "la filial"},
		{magyar: "megrendelés",spanyol: "el pedido"},
		{magyar: "munkanélküliség",spanyol: "el desempleo"},
		{magyar: "pénz",spanyol: "el dinero"},
		{magyar: "pénzügyek",spanyol: "las finanzas"},
		{magyar: "piac",spanyol: "el mercado"},
		{magyar: "részvény",spanyol: "la acción"},
		{magyar: "részvényes",spanyol: "el/la accionista"},
		{magyar: "számla",spanyol: "la factura"},
		{magyar: "sztrájk",spanyol: "la huelga"},
		{magyar: "szufficit",spanyol: "el superávit"},
		{magyar: "tőke",spanyol: "el capital"},
		{magyar: "tőzsde",spanyol: "la bolsa"},
		{magyar: "tőzsdeindex",spanyol: "el índice bursátil"},
		{magyar: "ügyfél",spanyol: "el cliente"},
		{magyar: "ügylet",spanyol: "la transacción"},
		{magyar: "üzlet",spanyol: "el negocio"},
		{magyar: "választék",spanyol: "el surtido"},
		{magyar: "vállalat",spanyol: "la empresa"},
		{magyar: "vám",spanyol: "la aduana"},
		{magyar: "vásár",spanyol: "la feria"},
		{magyar: "verseny",spanyol: "la competencia"}
	],
	politika: [
		{magyar: "állam",spanyol: "el estado"},
		{magyar: "belpolitika",spanyol: "la política interior"},
		{magyar: "demokrácia",spanyol: "la democracia"},
		{magyar: "diktatúra",spanyol: "la dictadura"},
		{magyar: "diplomácia",spanyol: "la diplomacia"},
		{magyar: "ellenzék",spanyol: "la oposición"},
		{magyar: "elnök",spanyol: "el presidente"},
		{magyar: "jelölt",spanyol: "el candidato"},
		{magyar: "kampány",spanyol: "la campaña"},
		{magyar: "képviselő",spanyol: "el diputado"},
		{magyar: "kisebbség",spanyol: "la minoría"},
		{magyar: "koalíció",spanyol: "la coalición"},
		{magyar: "kormány",spanyol: "el gobierno"},
		{magyar: "külpolitika",spanyol: "la política exterior"},
		{magyar: "miniszter",spanyol: "el ministro"},
		{magyar: "miniszterelnök",spanyol: "el primer ministro"},
		{magyar: "minisztérium",spanyol: "el ministerio"},
		{magyar: "mozgalom",spanyol: "el movimiento"},
		{magyar: "népszavazás",spanyol: "el plebiscito/referendo"},
		{magyar: "parlament",spanyol: "el parlamento"},
		{magyar: "párt",spanyol: "el partido"},
		{magyar: "politikus",spanyol: "el político"},
		{magyar: "puccs",spanyol: "el golpe de Estado"},
		{magyar: "szavazat",spanyol: "el voto"},
		{magyar: "szólásszabadság",spanyol: "la libertad de expresión"},
		{magyar: "szóvivő",spanyol: "el/la portavoz"},
		{magyar: "többség",spanyol: "la mayoría"},
		{magyar: "tüntetés",spanyol: "la manifestación"},
		{magyar: "tüntető",spanyol: "el/la manifestante"},
		{magyar: "választások",spanyol: "las elecciones"},
		{magyar: "választási",spanyol: "electoral"}
	],
	idojaras: [
		{magyar: "áradás",spanyol: "la inundación"},
		{magyar: "aszály",spanyol: "la sequía"},
		{magyar: "beborul",spanyol: "anublarse"},
		{magyar: "borult",spanyol: "cubierto"},
		{magyar: "ciklon",spanyol: "el ciclón"},
		{magyar: "csapadék",spanyol: "precipitaciones"},
		{magyar: "derült",spanyol: "despejado"},
		{magyar: "előrejelzés",spanyol: "el pronóstico, la predicción"},
		{magyar: "enyhe",spanyol: "templado, moderado"},
		{magyar: "esik",spanyol: "llover"},
		{magyar: "eső",spanyol: "la lluvia"},
		{magyar: "felhő",spanyol: "la nube"},
		{magyar: "felhős",spanyol: "nuboso, nublado"},
		{magyar: "felhőszakadás",spanyol: "la lluvia torrencial"},
		{magyar: "felhőzet",spanyol: "la nubosidad"},
		{magyar: "fúj a szél",spanyol: "hace viento"},
		{magyar: "gyenge",spanyol: "flojo, débil"},
		{magyar: "havazás",spanyol: "la nevada"},
		{magyar: "havazik",spanyol: "nevar"},
		{magyar: "heves",spanyol: "intenso"},
		{magyar: "hideg",spanyol: "(el) frío"},
		{magyar: "hóvihar",spanyol: "la ventisca"},
		{magyar: "hőingadozás",spanyol: "la amplitud térmica"},
		{magyar: "hőmérséklet",spanyol: "la temperatura"},
		{magyar: "hőség",spanyol: "la canícula, el calor"},
		{magyar: "hurrikán",spanyol: "el huracán"},
		{magyar: "hűvös",spanyol: "fresco"},
		{magyar: "időjárás",spanyol: "el tiempo"},
		{magyar: "időjárásjelentés",spanyol: "el boletín / el parte meteorológico"},
		{magyar: "jégeső",spanyol: "el granizo"},
		{magyar: "köd",spanyol: "la niebla, la bruma"},
		{magyar: "ködös",spanyol: "nebuloso"},
		{magyar: "légnyomás",spanyol: "la presión atmosférica"},
		{magyar: "meleg (mn.)",spanyol: "caliente"},
		{magyar: "mennydörgés",spanyol: "el trueno"},
		{magyar: "monszun",spanyol: "el monzón"},
		{magyar: "napos",spanyol: "soleado"},
		{magyar: "páratartalom",spanyol: "la humedad"},
		{magyar: "süt a nap",spanyol: "hace sol"},
		{magyar: "szél",spanyol: "el viento"},
		{magyar: "szellő",spanyol: "la brisa"},
		{magyar: "szemerkélő eső",spanyol: "la llovizna"},
		{magyar: "változékony",spanyol: "inestable"},
		{magyar: "vihar",spanyol: "la tempestad"},
		{magyar: "villám",spanyol: "el relámpago"},
		{magyar: "zivatar",spanyol: "chubascos, la tormenta"},
		{magyar: "zúzmara",spanyol: "la escarcha"}
	]
}



let word = [
	// egyéb (-3)
	// saját
	// 1. lecke (-5)
	{magyar: "Jó napot! (délelőtt)",spanyol: "¡Buenos días!"},
	{magyar: "Jó napot! (délután)",spanyol: "¡Buenas tardes!"},
	{magyar: "Jó estét!",spanyol: "¡Buenas noches!"},
	{magyar: "Hogy van?",spanyol: "¿Qué tal?"},
	{magyar: "jól",spanyol: "bien"},
	{magyar: "köszönöm",spanyol: "gracias "},
	{magyar: "És te?",spanyol: "¿Y tú?"},
	{magyar: "mint mindig",spanyol: "regular"},
	{magyar: "telefon",spanyol: "el teléfono "},
	{magyar: "Halló?",spanyol: "¿Diga?"},
	{magyar: "lenni",spanyol: "ser"},
	{magyar: "úr",spanyol: "el señor"},
	{magyar: "Müller vagyok",spanyol: "soy el señor M."},
	{magyar: "a Südgut vállalattól",spanyol: "de la empresa S."},
	{magyar: "Hogyan?",spanyol: "¿Cómo?"},
	{magyar: "Mi?",spanyol: "¿Qué?"},
	{magyar: "Ki?",spanyol: "¿Quién?"},
	{magyar: "Németországból",spanyol: "de Alemania"},
	{magyar: "-ból/-ből",spanyol: "de"},
	{magyar: "igen",spanyol: "sí "},
	{magyar: "Ön ki?",spanyol: "¿Quién es usted?"},
	{magyar: "főnök/főnöknő",spanyol: "el jefe/la jefa"},
	{magyar: "virág",spanyol: "la flor"},
	{magyar: "lámpa",spanyol: "la lámpara "},
	{magyar: "levél",spanyol: "la carta"},
	{magyar: "asztal",spanyol: "la mesa"},
	{magyar: "szék",spanyol: "la silla "},
	{magyar: "számológép",spanyol: "la calculadora "},
	{magyar: "nyomtató",spanyol: "la impresora"},
	{magyar: "iroda",spanyol: "la oficina"},
	{magyar: "lemez",spanyol: "el disquete"},
	{magyar: "könyv",spanyol: "el libro"},
	{magyar: "papír",spanyol: "el papel"},
	{magyar: "számítógép",spanyol: "el ordenador"},
	{magyar: "telefon",spanyol: "el teléfono "},
	{magyar: "falióra",spanyol: "el reloj"},
	{magyar: "fax",spanyol: "el fax"},
	{magyar: "toll",spanyol: "el bolígrafo"},
	{magyar: "az emberek",spanyol: "la gente"},
	{magyar: "exportálni",spanyol: "exportar"},
	{magyar: "hát",spanyol: "bueno"},
	{magyar: "olivaolaj",spanyol: "el aceite de oliva"},
	{magyar: "olajbogyó",spanyol: "la aceituna "},
	{magyar: "bor",spanyol: "el vino"},
	{magyar: "narancs",spanyol: "la naranja"},
	{magyar: "eper",spanyol: "la fresa"},
	{magyar: "fokhagyma",spanyol: "el ajo"},
	{magyar: "paprika",spanyol: "el pimiento"},
	{magyar: "oké, világos",spanyol: "vale"},
	{magyar: "Hová?",spanyol: "¿Adónde?"},
	{magyar: "Honnan?",spanyol: "¿De dónde?"},
	{magyar: "nagyon",spanyol: "muy"},
	{magyar: "nem",spanyol: "no"},
	{magyar: "Olaszországból",spanyol: "de Italia"},
	{magyar: "Hollandia",spanyol: "Holanda"},
	{magyar: "Belgium",spanyol: "Bélgica"},
	{magyar: "Nagy-Britannia",spanyol: "Gran-Bretaña "},
	{magyar: "Írország",spanyol: "Irlanda"},
	{magyar: "Portugália",spanyol: "Portugal"},
	{magyar: "Spanyolország",spanyol: "España"},
	{magyar: "Svájc",spanyol: "Suiza"},
	{magyar: "Svédország",spanyol: "Suecia"},
	{magyar: "Finnország",spanyol: "Finlandia"},
	{magyar: "Dánia",spanyol: "Dinamarca"},
	{magyar: "Oroszország",spanyol: "Rusia"},
	{magyar: "Lengyelország",spanyol: "Polonia"},
	{magyar: "Csehország",spanyol: "República Checa"},
	{magyar: "Görögország",spanyol: "Grecia"},
	{magyar: "Magyarország",spanyol: "Hungria"},
	{magyar: "szám",spanyol: "el número "},
	{magyar: "0",spanyol: "cero"},
	{magyar: "1",spanyol: "uno"},
	{magyar: "2",spanyol: "dos"},
	{magyar: "3",spanyol: "tres"},
	{magyar: "4",spanyol: "cuatro"},
	{magyar: "5",spanyol: "cinco"},
	{magyar: "6",spanyol: "seis"},
	{magyar: "7",spanyol: "siete"},
	{magyar: "8",spanyol: "ocho"},
	{magyar: "9",spanyol: "nueve"},
	{magyar: "10",spanyol: "diez"},
	{magyar: "típus",spanyol: "el tipo"},
	{magyar: "itt",spanyol: "aquí"},
	{magyar: "ott",spanyol: "ahí"},
	{magyar: "létezni",spanyol: "existir"},
	{magyar: "két éve",spanyol: "desde hase dos años"},
	{magyar: "dolgozni",spanyol: "trabajar"},
	{magyar: "személy",spanyol: "la persona"},
	{magyar: "könyvelő",spanyol: "el contable"},
	{magyar: "titkárnő",spanyol: "la secretaria"},
	{magyar: "mivel, hát",spanyol: "pues"},
	{magyar: "köszönet az információért",spanyol: "muchas gracias por la información "},
	{magyar: "ez minden",spanyol: "eso es todo"},
	{magyar: "Viszlát a legközelebbi alkalomig!",spanyol: "¡Adiós, hasta la próxima!"},
	{magyar: "Tűzoltóság",spanyol: "los Bomberos"},
	{magyar: "Mentők",spanyol: "la Ambulancia"},
	{magyar: "Rendőrség",spanyol: "la Policía "},
	{magyar: "mérnök",spanyol: "el ingeniero"},
	{magyar: "taxisofőr",spanyol: "el taxista"},
	{magyar: "énekes",spanyol: "el cantante"},
	{magyar: "énekelni",spanyol: "cantar"},
	{magyar: "tangó",spanyol: "el tango"},
	{magyar: "tanár",spanyol: "el profesor"},
	{magyar: "tanárnő",spanyol: "la profesora"},
	{magyar: "Nézd!",spanyol: "¡Mira!"},
	{magyar: "nézni",spanyol: "mirar"},
	{magyar: "tanulni",spanyol: "estudiar"},
	{magyar: "az egyetemen",spanyol: "en la universidad"},
	{magyar: "de",spanyol: "pero"},
	{magyar: "taxisofőrként dolgozni",spanyol: "trabajar de taxista"},
	{magyar: "mivel",spanyol: "es que"},
	{magyar: "szükség van valamire",spanyol: "necesitar"},
	{magyar: "pénz",spanyol: "el dinero"},
	{magyar: "most",spanyol: "ahora"},
	{magyar: "tanítani",spanyol: "enseñar"},
	{magyar: "nyelv",spanyol: "el idioma"},
	{magyar: "hihetetlen",spanyol: "increíble "},
	{magyar: "jelent",spanyol: "significar"},
	{magyar: "-val/-vel",spanyol: "con"},
	{magyar: "barát",spanyol: "el amigo"},
	{magyar: "kávé",spanyol: "el café"},
	{magyar: "sajnálom",spanyol: "lo siento"},
	{magyar: "birtokolni",spanyol: "tener"},
	{magyar: "telefonálni",spanyol: "hablar por teléfono"},
	{magyar: "részére, -nak/-nek",spanyol: "para"},
	{magyar: "dokumentum",spanyol: "el documento"},
	{magyar: "hát igen, nos",spanyol: "pues"},
	{magyar: "probléma",spanyol: "el problema"},
	{magyar: "idő",spanyol: "el tiempo"},
	{magyar: "nincs időm",spanyol: "yo no tengo tiempo"},
	{magyar: "nyugalom",spanyol: "la tranquilidad"},
	{magyar: "így, úgy",spanyol: "así"},
	{magyar: "működik",spanyol: "funcionar"},
	{magyar: "beszélni",spanyol: "hablar"},
	{magyar: "egy pillanat",spanyol: "un momentito"},
	{magyar: "Mi van? Mi történt?",spanyol: "¿Qué pasa?"},
	{magyar: "történni",spanyol: "pasar"},
	{magyar: "ideges",spanyol: "nervioso/nerviosa"},
	{magyar: "utazni",spanyol: "viajar"},
	{magyar: "Mi lenne, ha..?",spanyol: "¿Qué tal…?"},
	{magyar: "látogatni",spanyol: "visitar"},
	{magyar: "múzeum",spanyol: "el museo"},
	{magyar: "múzeumot látogatni",spanyol: "visitar museos"},
	{magyar: "igazad van",spanyol: "tienes rezón"},
	{magyar: "cégvezető (férfi)",spanyol: "el gerente"},
	{magyar: "cégvezető (nő)",spanyol: "la gerente"},
	{magyar: "export",spanyol: "la exportación "},
	{magyar: "angol",spanyol: "el inglés"},
	{magyar: "német",spanyol: "el alemán"},
	{magyar: "exportáló vállalat",spanyol: "la empresa de exportación"},
	{magyar: "szálloda, hotel",spanyol: "el hotel"},
	{magyar: "keres",spanyol: "buscar"},
	{magyar: "szakács",spanyol: "el cocinero"},
	{magyar: "szakácsnő",spanyol: "la cocinera"},
	{magyar: "pincér",spanyol: "el camarero"},
	{magyar: "pincérnő",spanyol: "la camarera"},
	{magyar: "spanyol",spanyol: "el español"},
	{magyar: "spanyoltanár",spanyol: "el profesor de español"},
	{magyar: "neked",spanyol: "para ti"},
	{magyar: "kérem",spanyol: "por favor"},
	{magyar: "menni",spanyol: "ir"},
	{magyar: "nap",spanyol: "el día"},
	{magyar: "szabadság, üdülés",spanyol: "las vacaciónes"},
	{magyar: "De jó!",spanyol: "¡Qué bien!"},
	{magyar: "Galícia",spanyol: "Galicia"},
	{magyar: "barátnő",spanyol: "una amiga"},
	{magyar: "Miért?",spanyol: "¿Por qué?"},
	{magyar: "mert",spanyol: "porque "},
	{magyar: "kérdezni",spanyol: "preguntar"},
	{magyar: "semmi",spanyol: "nada"},
	{magyar: "nincs mit",spanyol: "de nada"},
	{magyar: "autó",spanyol: "el coche"},
	{magyar: "repülő",spanyol: "el avión"},
	{magyar: "vonat",spanyol: "el tren"},
	{magyar: "vonattal megyünk",spanyol: "vamos en tren"},
	{magyar: "világos",spanyol: "claro"},
	{magyar: "katedrális",spanyol: "la catedral"},
	{magyar: "szép",spanyol: "bonito/bonita"},
	{magyar: "ilyen az élet",spanyol: "así es la vida"},
	{magyar: "kapcsolatot tartani",spanyol: "mantener el contacto"},
	{magyar: "fontos",spanyol: "importante"},
	{magyar: "vevő, ügyfél",spanyol: "el cliente"},
	{magyar: "főváros",spanyol: "la capital"},
	{magyar: "város",spanyol: "la ciudad"},
	{magyar: "van, létezik",spanyol: "hay"},
	{magyar: "kultúra",spanyol: "la cultura"},
	{magyar: "befejezni, végezni",spanyol: "terminar"},
	{magyar: "hal",spanyol: "el pescado"},
	{magyar: "tenger",spanyol: "el mar"},
	{magyar: "jó, ízletes",spanyol: "rico/rica"},
	{magyar: "hagyomány, tradíció",spanyol: "la tradición"},
	{magyar: "például",spanyol: "por ejemplo"},
	{magyar: "ünnepség",spanyol: "la fiesta"},
	{magyar: "ezért",spanyol: "por eso"},
	{magyar: "kivándorlás, emigrálás",spanyol: "la emigración"},
	{magyar: "termék",spanyol: "el producto"},
	{magyar: "ők spanyolok",spanyol: "son españoles"},
	{magyar: "érdeklődni valami iránt",spanyol: "tener interés en"},
	{magyar: "érdeklődés",spanyol: "el interés"},
	{magyar: "kérni",spanyol: "pedir"},
	{magyar: "olasz férfi",spanyol: "el italiano"},
	{magyar: "olasz nő",spanyol: "la italiana"},
	{magyar: "francia férfi",spanyol: "el francés"},
	{magyar: "francia nő",spanyol: "la francesa"},
	{magyar: "spanyol férfi",spanyol: "el español"},
	{magyar: "spanyol nő",spanyol: "la española"},
	{magyar: "belga férfi",spanyol: "el belga"},
	{magyar: "belga nő",spanyol: "la belga"},
	{magyar: "arab férfi",spanyol: "el árabe"},
	{magyar: "arab nő",spanyol: "la árabe"},
	{magyar: "olasz nyelv",spanyol: "italiano"},
	{magyar: "német nyelv",spanyol: "alemán"},
	{magyar: "spanyol nyelv",spanyol: "español"},
	{magyar: "a német város",spanyol: "la ciudad alemana"},
	{magyar: "a német falu",spanyol: "el pueblo alemán"},
		// saját
	// (-7)
	{magyar: "nap",spanyol: "el día"},
{magyar: "hét",spanyol: "la semana"},
{magyar: "hétvége",spanyol: "el fin de semana"},
{magyar: "hónap",spanyol: "el mes"},
{magyar: "év",spanyol: "el año"},
{magyar: "január",spanyol: "enero"},
{magyar: "február",spanyol: "febrero"},
{magyar: "március",spanyol: "marzo"},
{magyar: "április",spanyol: "abril"},
{magyar: "május",spanyol: "mayo"},
{magyar: "június",spanyol: "junio"},
{magyar: "július",spanyol: "julio"},
{magyar: "augusztus",spanyol: "agosto"},
{magyar: "szeptember",spanyol: "septiembre"},
{magyar: "október",spanyol: "octubre"},
{magyar: "november",spanyol: "noviembre"},
{magyar: "december",spanyol: "diciembre"},
{magyar: "hétfő",spanyol: "lunes"},
{magyar: "kedd",spanyol: "martes"},
{magyar: "szerda",spanyol: "miércoles"},
{magyar: "csütörtök",spanyol: "jueves"},
{magyar: "péntek",spanyol: "viernes"},
{magyar: "szombat",spanyol: "sábado"},
{magyar: "vasárnap",spanyol: "domingo"},
{magyar: "naptár",spanyol: "el calendario"},
{magyar: "dátum",spanyol: "la fecha"},
{magyar: "június másodika, kedd",spanyol: "martes, dos de junio"},
{magyar: "elseje",spanyol: "el primero"},
{magyar: "másodika",spanyol: "el dos"},
{magyar: "harmadika",spanyol: "el tres"},
{magyar: "negyedike",spanyol: "el cuatro"},
{magyar: "tegnap",spanyol: "ayer"},
{magyar: "tegnap reggel",spanyol: "ayer por la mañana"},
{magyar: "tegnap este",spanyol: "anoche"},
{magyar: "ma",spanyol: "hoy"},
{magyar: "ma reggel",spanyol: "esta mañana "},
{magyar: "ma este",spanyol: "esta tarde"},
{magyar: "holnap",spanyol: "mañana"},
{magyar: "holnap reggel",spanyol: "mañana por la mañana"},
{magyar: "holnap este",spanyol: "mañana por la tarde"},
{magyar: "holnapután",spanyol: "pasado mañana"},
{magyar: "tegnapelőtt",spanyol: "anteayer"},
{magyar: "jövő hétfőn",spanyol: "el próximo lunes"},
{magyar: "jövő héten",spanyol: "la semana próxima"},
{magyar: "nekem",spanyol: "me"},
{magyar: "neked",spanyol: "te"},
{magyar: "neki",spanyol: "le"},
{magyar: "Önnek",spanyol: "le"},
{magyar: "nekünk",spanyol: "nos"},
{magyar: "nektek",spanyol: "os"},
{magyar: "nekik",spanyol: "les"},
{magyar: "Önöknek",spanyol: "les"},
{magyar: "engem",spanyol: "me"},
{magyar: "téged",spanyol: "te"},
{magyar: "őt",spanyol: "lo/la"},
{magyar: "Önt",spanyol: "lo"},
{magyar: "minket",spanyol: "nos"},
{magyar: "titeket",spanyol: "os"},
{magyar: "őket",spanyol: "los/las"},
{magyar: "Önöket",spanyol: "los/las"},
{magyar: "család",spanyol: "la familia"},
{magyar: "apa",spanyol: "el padre"},
{magyar: "anya",spanyol: "la madre"},
{magyar: "fiútestvér",spanyol: "el hermano"},
{magyar: "lánytestvér",spanyol: "la hermana"},
{magyar: "nagypapa",spanyol: "el abuelo"},
{magyar: "nagymama",spanyol: "la abuela"},
{magyar: "szülők",spanyol: "los padres"},
{magyar: "feleség",spanyol: "la mujer"},
{magyar: "férj",spanyol: "el marido"},
	//kettes lecke
	//-9
	{magyar: "Melyiké?",spanyol: "¿De quién?"},
{magyar: "tudni",spanyol: "saber"},
{magyar: "Tudsz valamit róla?",spanyol: "¿Sabes algo de ella?"},
{magyar: "együtt",spanyol: "juntos/juntas"},
{magyar: "alkalmazott",spanyol: "el empleado"},
{magyar: "egyébként",spanyol: "por cierto"},
{magyar: "ami",spanyol: "que"},
{magyar: "megbocsátani",spanyol: "perdonar"},
{magyar: "Bocsáss meg!",spanyol: "¡Perdona!"},
{magyar: "segítség",spanyol: "la ayuda"},
{magyar: "enyém",spanyol: "mi"},
{magyar: "Nem tudom, hol vannak.",spanyol: "Yo no sé dónde están."},
{magyar: "felhívom Mariát",spanyol: "llamo a Maria"},
{magyar: "a főnököt kérdezni",spanyol: "preguntar a la jefa"},
{magyar: "aztán",spanyol: "después "},
{magyar: "Rendben, egyetértünk.",spanyol: "de acuerdo"},
{magyar: "Igaz?",spanyol: "¿Verdad?"},
{magyar: "táj",spanyol: "el paisaje"},
{magyar: "fantasztikus",spanyol: "fantástico/fantástica"},
{magyar: "ezen kívül",spanyol: "además "},
{magyar: "kedves",spanyol: "amable"},
{magyar: "nyitott",spanyol: "abierto/abierta"},
{magyar: "ez igaz",spanyol: "es verdad"},
{magyar: "az igazság",spanyol: "la verdad"},
{magyar: "elbűvölő",spanyol: "encantador/a"},
{magyar: "nyugodt",spanyol: "tranquilo/a"},
{magyar: "stresszes",spanyol: "estresante"},
{magyar: "unalmas",spanyol: "aburrido"},
{magyar: "normális",spanyol: "normal"},
{magyar: "vőlegény,barát",spanyol: "el novio"},
{magyar: "viccelni",spanyol: "bromear"},
{magyar: "valójában",spanyol: "en realidad"},
{magyar: "a valóság",spanyol: "la realidad"},
{magyar: "használni",spanyol: "usar"},
{magyar: "csak",spanyol: "sólo"},
{magyar: "másik",spanyol: "otro/otra"},
{magyar: "veszélyes",spanyol: "peligroso/peligrosa"},
{magyar: "sok",spanyol: "mucho/mucha"},
{magyar: "vírus",spanyol: "el virus"},
{magyar: "látni",spanyol: "ver"},
{magyar: "új",spanyol: "nuevo/nueva"},
{magyar: "név",spanyol: "el nombre"},
{magyar: "nehéz,bonyolult",spanyol: "dificil"},
{magyar: "különböző",spanyol: "diferente"},
{magyar: "található, van",spanyol: "estar"},
{magyar: "utca",spanyol: "la calle"},
{magyar: "dél",spanyol: "el sur"},
{magyar: "folyó",spanyol: "el rio"},
{magyar: "híres",spanyol: "famoso/famosa"},
{magyar: "a közelében",spanyol: "cerca de"},
{magyar: "ahol",spanyol: "donde"},
{magyar: "torony",spanyol: "la torre"},
{magyar: "magas",spanyol: "alto/alta"},
{magyar: "műemlék",spanyol: "el monumento"},
{magyar: "érdekes",spanyol: "interesante"},
{magyar: "távol valamitől",spanyol: "lejos de"},
{magyar: "tér",spanyol: "la plaza"},
{magyar: "park",spanyol: "el parque"},
{magyar: "kert",spanyol: "el jardin"},
{magyar: "eredeti, hiteles",spanyol: "auténtico "},
{magyar: "bikaviadal",spanyol: "la corrida de toros"},
{magyar: "egy keveset",spanyol: "un poco"},
{magyar: "kérdés",spanyol: "la pregunta"},
{magyar: "fogyasztani",spanyol: "consumir"},
{magyar: "tipikus",spanyol: "tipico/tipica"},
{magyar: "kapni",spanyol: "recibir"},
{magyar: "ország",spanyol: "el país"},
{magyar: "küldeni",spanyol: "mandar"},
{magyar: "ma",spanyol: "hay"},
{magyar: "üveg",spanyol: "la botella"},
{magyar: "ház",spanyol: "la casa"},
{magyar: "eldönteni",spanyol: "decidir"},
{magyar: "lakni, élni",spanyol: "vivir"},
{magyar: "Hogy hívják?",spanyol: "¿Cómo se llama usted?"},
{magyar: "Hol lakik?",spanyol: "¿Dónde vive usted?"},
{magyar: "A nevem../Engem ...-nak hívnak.",spanyol: "me llamo"},
{magyar: "nevezni, hívni",spanyol: "llamar"},
{magyar: "írni",spanyol: "escribir"},
{magyar: "első",spanyol: "primero"},
{magyar: "második",spanyol: "segundo"},
{magyar: "vezetéknév, családnév",spanyol: "el primer apellido"},
	{magyar: "a családom",spanyol: "mi familia"},
{magyar: "fénykép",spanyol: "la fotorgrafia"},
{magyar: "Kik?",spanyol: "¿Quiénes?"},
{magyar: "szülők",spanyol: "los padres"},
{magyar: "nagyszülők",spanyol: "los abuelos"},
{magyar: "testvérek",spanyol: "los hermanos"},
{magyar: "Latin Amerika",spanyol: "Latinoamérica"},
{magyar: "apa",spanyol: "el padre"},
{magyar: "anya",spanyol: "la madre"},
{magyar: "Hány évesek a szüleid?",spanyol: "¿Cuántos años tienen tus padres?"},
{magyar: "fiútestvér",spanyol: "el hermano"},
{magyar: "lánytestvér",spanyol: "la hermana"},
{magyar: "nagypapa",spanyol: "el abuelo"},
{magyar: "nagymama",spanyol: "la abuela"},
{magyar: "nagy",spanyol: "grande"},
{magyar: "a mi családunk",spanyol: "nuestra familia"},
{magyar: "miénk",spanyol: "nuestro/nuestra"},
{magyar: "nagynéni",spanyol: "la tía"},
{magyar: "mindig",spanyol: "siempre"},
{magyar: "mondani",spanyol: "decir"},
{magyar: "unokaöccs",spanyol: "el sobrino"},
{magyar: "papa",spanyol: "el papá"},
{magyar: "unokanővér",spanyol: "la prima"},
{magyar: "kicsi",spanyol: "pequeño/a"},
{magyar: "hónap",spanyol: "el mes"},
{magyar: "lánygyermek",spanyol: "la hija"},
{magyar: "nagybácsi",spanyol: "el tío"},
{magyar: "mama",spanyol: "la mamá"},
{magyar: "az én bácsikám",spanyol: "mi tío"},
{magyar: "a te bácsikád",spanyol: "tu tío"},
{magyar: "az ő bácsikája",spanyol: "su tío"},
{magyar: "a mi bácsikánk",spanyol: "nuestro tío"},
{magyar: "a ti bácsikátok",spanyol: "vuestro tío"},
{magyar: "az ő bácsikájuk",spanyol: "su tío"},
{magyar: "a mi nénikénk",spanyol: "nuestra tía"},
{magyar: "a  ti nénikétek",spanyol: "vuestra tía"},
	{magyar: "fiatal",spanyol: "joven"},
{magyar: "még",spanyol: "todavia"},
{magyar: "Mexikó",spanyol: "México"},
{magyar: "ott",spanyol: "allí"},
{magyar: "régi",spanyol: "antiguo/a"},
{magyar: "modern",spanyol: "moderno/a"},
{magyar: "strand",spanyol: "la playa"},
{magyar: "jól vannak",spanyol: "están muy bien"},
{magyar: "rokon",spanyol: "el pariente"},
{magyar: "mexikói",spanyol: "mexicano/a"},
{magyar: "házas",spanyol: "casado/a"},
{magyar: "házasnak lenni",spanyol: "estar casado/a"},
{magyar: "asszony,feleség",spanyol: "la mujer"},
{magyar: "perui",spanyol: "peruano/a"},
{magyar: "nőtlen, hajadon",spanyol: "soltero/a"},
{magyar: "nőtlennek, hajadonnak lenni",spanyol: "estar soltero/a"},
{magyar: "logikus",spanyol: "lógico"},
{magyar: "újságíró",spanyol: "el periodista"},
{magyar: "enni, inni",spanyol: "tomar"},
{magyar: "reggeli",spanyol: "el desayuno"},
{magyar: "reggelire",spanyol: "en el desayuno"},
{magyar: "tejeskávé",spanyol: "el café con leche"},
{magyar: "kétszersült",spanyol: "la tostada"},
{magyar: "inni",spanyol: "beber"},
{magyar: "tea",spanyol: "el té"},
{magyar: "enni",spanyol: "comer"},
{magyar: "teljes kiőrlésű kenyér",spanyol: "el pan integral"},
{magyar: "vaj",spanyol: "la mantequilla"},
{magyar: "lekvár",spanyol: "la mermelada"},
{magyar: "sajt",spanyol: "el queso"},
{magyar: "kolbász",spanyol: "la salchicha"},
{magyar: "étel",spanyol: "la comida"},
{magyar: "erős",spanyol: "fuerte"},
{magyar: "erősebb, kiadósabb",spanyol: "más fuerte"},
{magyar: "ebéd",spanyol: "el almuerzo"},
{magyar: "vacsora",spanyol: "la cena"},
{magyar: "hús",spanyol: "la carne"},
{magyar: "zöldség",spanyol: "la verdura"},
{magyar: "gyümölcs",spanyol: "la fruta"},
{magyar: "sütemény",spanyol: "el pastel"},
{magyar: "sok hal",spanyol: "mucho pescado"},
{magyar: "sok sütemény",spanyol: "muchos pasteles"},
{magyar: "sok hús",spanyol: "mucha carne"},
{magyar: "sok étel",spanyol: "muchas comidas"},
{magyar: "Magyarországon magyarul beszélnek.",spanyol: "En Hungria se habla hungaro."},
{magyar: "Hogy írják a nevét?",spanyol: "¿Cómo se escribe su nombre?"},
{magyar: "Julio, aki Kubában él, spanyol.",spanyol: "Julio, que vive en Cuba, es español."},
{magyar: "Az utca, ahol laksz, messze van innen.",spanyol: "La calle donde vives está lejos."},
{magyar: "igaz",spanyol: "correcto"},
{magyar: "hamis",spanyol: "falso"},
{magyar: "mialatt",spanyol: "mientras"},
{magyar: "informatika",spanyol: "la informática"},
{magyar: "javítani",spanyol: "reparar"},
{magyar: "furcsa mód",spanyol: "curiosamente"},
{magyar: "talán",spanyol: "quizá"},
{magyar: "mert, mivel",spanyol: "pues"},
{magyar: "férfi",spanyol: "el hombre"},
{magyar: "elmagyarázni, hogy",spanyol: "explicar que"},
{magyar: "neki",spanyol: "para ella"},
{magyar: "kivéve",spanyol: "excepto"},
	{magyar: "lenni",spanyol: "ser",spanyol2: ["soy","eres","es","somos","sois","son"]},
{magyar: "exportálni",spanyol: "exportar",spanyol2: ["exporto","exportas","exporta","exportamos","exportáis","exportan"]},
{magyar: "dolgozni",spanyol: "trabajar",spanyol2: ["trabajo","trabajas","trabaja","trabajamos","trabajáis","trabajan"]},
{magyar: "létezni",spanyol: "existir",spanyol2: ["existo","existes","existe","existimos","existís","existen"]},
{magyar: "énekelni",spanyol: "cantar",spanyol2: ["canto","cantas","canta","cantamos","cantáis","cantan"]},
{magyar: "nézni",spanyol: "mirar",spanyol2: ["miro","miras","mira","miramos","miráis","miran"]},
{magyar: "szükség van valamire",spanyol: "necesitar",spanyol2: ["necesito","necesitas","necesita","necesitamos","necesitáis","necesitan"]},
{magyar: "tanulni",spanyol: "estudiar",spanyol2: ["estudio","estudias","estudia","estudiamos","estudiáis","estudian"]},
{magyar: "tanítani",spanyol: "enseñar",spanyol2: ["enseño","enseñas","enseña","enseñamos","enseñáis","enseñan"]},
{magyar: "jelenteni",spanyol: "significar",spanyol2: ["significo","significas","significa","significamos","significáis","significan"]},
{magyar: "beszélni",spanyol: "hablar",spanyol2: ["hablo","hablas","habla","hablamos","habláis","hablan"]},
{magyar: "birtokolni",spanyol: "tener",spanyol2: ["tengo","tienes","tiene","teneamos","tenéis","tienen"]},
{magyar: "történni",spanyol: "pasar",spanyol2: ["paso","pasas","pasa","pasamos","pasáis","pasan"]},
{magyar: "látogatni",spanyol: "visitar",spanyol2: ["visito","visitas","visita","visitamos","visitáis","visitan"]},
{magyar: "menni",spanyol: "ir",spanyol2: ["voy","vas","va","vamos","váis","van"]},
{magyar: "kérni",spanyol: "pedir",spanyol2: ["pido","pides","pide","pedimos","pedís","piden"]},
{magyar: "keresni",spanyol: "buscar",spanyol2: ["busco","buscas","busca","buscamos","buscáis","buscan"]},
{magyar: "tudni",spanyol: "saber",spanyol2: ["sabo","sabes","sabe","sabemos","sabéis","saben"]},
{magyar: "megbocsátni",spanyol: "perdonar",spanyol2: ["perdona","perdonas","perdona","perdonamos","perdonáis","perdonan"]},
{magyar: "lenni, található valahol",spanyol: "estar",spanyol2: ["estoy","estás","está","estamos","estáis","están"]},
{magyar: "felhívni, hívni, nevezni",spanyol: "llamar",spanyol2: ["llamo","llamas","llama","llamamos","llamáis","llaman"]},
{magyar: "használni",spanyol: "usar",spanyol2: ["uso","usas","usa","usamos","usáis","usan"]},
{magyar: "látni",spanyol: "ver",spanyol2: ["veo","ves","ve","vemos","veis","ven"]},
{magyar: "fogyasztani",spanyol: "consumir",spanyol2: ["consumo","consumes","consume","consumimos","consumís","consumen"]},
{magyar: "kapni",spanyol: "recibir",spanyol2: ["recibo","recibes","recibe","recibimos","ricibís","reciben"]},
{magyar: "írni",spanyol: "escribir",spanyol2: ["escribo","escribes","escribe","escribimos","escribís","escriben"]},
{magyar: "eldönteni",spanyol: "decidir",spanyol2: ["decido","decides","decide","decidimos","decidís","deciden"]},
{magyar: "küldeni",spanyol: "mandar",spanyol2: ["mando","mandas","manda","mandamos","mandáis","mandan"]},
{magyar: "lakni, élni",spanyol: "vivir",spanyol2: ["vivo","vives","vive","vivimos","vivís","viven"]},
	{magyar: "örülni",spanyol: "alegrarse",spanyol2: ["me alegro","te alegras","se alegra","nos alegramos","os algráis","se alegran"]},
{magyar: "mondani",spanyol: "decir",spanyol2: ["digo","dices","dice","decimos","decís","dicen"]},
{magyar: "enni, inni",spanyol: "tomar",spanyol2: ["tomo","tomas","toma","tomamos","tomáis","toman"]},
{magyar: "inni",spanyol: "beber",spanyol2: ["bebo","bebes","bebe","bebemos","bebéis","beben"]},
{magyar: "enni",spanyol: "comer",spanyol2: ["como","comes","come","comemos","coméis","comen"]},
{magyar: "reggelizni",spanyol: "desayunar",spanyol2: ["desayuno","desayunas","deayuna","desayunamos","desayunáis","desayunan"]}
]